### ISSUE TITLE
from where can i get these  values.

### ISSUE THREAD

**Issue by ashokbg** [lawloretienne/Loop#4]
Error:(55, 51) error: cannot find symbol variable vimeo_state
Error:(61, 43) error: cannot find symbol variable client_redirect_uri
Error:(148, 42) error: cannot find symbol variable cast_app_id
and please mention still anything is needed  to run this project because right now in readme.md you mentioned only client_id, client_secret values  are needed to run.

**Comment by lawloretienne** [comment]
I have updated the README which an explanation of where to get these values.  Let me know if there is still an issue.
